import { findResourceKindFromCloudResourceIdentifier } from './findResourceKindFromCloudResourceIdentifier';

export const TEST_PROJECT_ID = '12345';
const TEST_LOCATION = 'us-east1';
const TEST_PROJECT_NUMBER = '67890';
const TEST_REGION = 'us-east2';
const TEST_ZONE = 'us-east3';
const TEST_CLUSTER = 'test';
const GENERIC_ID = 'abcdef12345';
export const TEST_PROJECT_NAME = 'testy-testerson';
export const testResourceIdentifiers = {
  [`//cloudfunctions.googleapis.com/projects/${TEST_PROJECT_ID}/locations/${TEST_LOCATION}/functions/${GENERIC_ID}`]:
    'cloudfunctions.googleapis.com/CloudFunction',
  [`//cloudresourcemanager.googleapis.com/organizations/${GENERIC_ID}`]:
    'cloudresourcemanager.googleapis.com/Organization',
  [`//cloudresourcemanager.googleapis.com/folders/${GENERIC_ID}`]:
    'cloudresourcemanager.googleapis.com/Folder',
  [`//cloudresourcemanager.googleapis.com/projects/${TEST_PROJECT_NAME}`]:
    'cloudresourcemanager.googleapis.com/Project',
  [`//cloudresourcemanager.googleapis.com/projects/${TEST_PROJECT_ID}`]:
    'cloudresourcemanager.googleapis.com/Project',
  [`//run.googleapis.com/projects/${TEST_PROJECT_ID}/locations/${TEST_LOCATION}/domainmappings/${GENERIC_ID}`]:
    'run.googleapis.com/DomainMapping',
  [`//run.googleapis.com/projects/${TEST_PROJECT_ID}/locations/${TEST_LOCATION}/revisions/${GENERIC_ID}`]:
    'run.googleapis.com/Revision',
  [`//run.googleapis.com/projects/${TEST_PROJECT_ID}/locations/${TEST_LOCATION}/services/${GENERIC_ID}`]:
    'run.googleapis.com/Service',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/regions/${TEST_REGION}/addresses/${GENERIC_ID}`]:
    'compute.googleapis.com/Address',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/addresses/${GENERIC_ID}`]:
    'compute.googleapis.com/GlobalAddress',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/autoscalers/${GENERIC_ID}`]:
    'compute.googleapis.com/Autoscaler',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/regions/${TEST_REGION}/autoscalers/${GENERIC_ID}`]:
    'compute.googleapis.com/Autoscaler',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/backendBuckets/${GENERIC_ID}`]:
    'compute.googleapis.com/BackendBucket',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/backendServices/${GENERIC_ID}`]:
    'compute.googleapis.com/BackendService',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/region/${TEST_REGION}/commitments/${GENERIC_ID}`]:
    'compute.googleapis.com/Commitment',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/disks/${GENERIC_ID}`]:
    'compute.googleapis.com/Disk',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/externalVpnGateways/${GENERIC_ID}`]:
    'compute.googleapis.com/ExternalVpnGateway',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/firewalls/${GENERIC_ID}`]:
    'compute.googleapis.com/Firewall',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/regions/${TEST_REGION}/forwardingRules/${GENERIC_ID}`]:
    'compute.googleapis.com/ForwardingRule',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/healthChecks/${GENERIC_ID}`]:
    'compute.googleapis.com/HealthCheck',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/httpHealthChecks/${GENERIC_ID}`]:
    'compute.googleapis.com/HttpHealthCheck',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/httpsHealthChecks/${GENERIC_ID}`]:
    'compute.googleapis.com/HttpsHealthCheck',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/images/${GENERIC_ID}`]:
    'compute.googleapis.com/Image',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/instances/${GENERIC_ID}`]:
    'compute.googleapis.com/Instance',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/instanceGroups/${GENERIC_ID}`]:
    'compute.googleapis.com/InstanceGroup',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/regions/${TEST_REGION}/instanceGroups/${GENERIC_ID}`]:
    'compute.googleapis.com/InstanceGroup',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/instanceGroupManager/${GENERIC_ID}`]:
    'compute.googleapis.com/InstanceGroupManager',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/regions/${TEST_REGION}/instanceGroupManager/${GENERIC_ID}`]:
    'compute.googleapis.com/InstanceGroupManager',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/instanceTemplates/${GENERIC_ID}`]:
    'compute.googleapis.com/InstanceTemplate',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/interconnects/${GENERIC_ID}`]:
    'compute.googleapis.com/Interconnect',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/regions/interconnectAttachments/${GENERIC_ID}`]:
    'compute.googleapis.com/InterconnectAttachment',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/licenses/${GENERIC_ID}`]:
    'compute.googleapis.com/License',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/networks/${GENERIC_ID}`]:
    'compute.googleapis.com/Network',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/networkEndpointGroups/${GENERIC_ID}`]:
    'compute.googleapis.com/NetworkEndpointGroup',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/nodeGroups/${GENERIC_ID}`]:
    'compute.googleapis.com/NodeGroup',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/regions/${TEST_REGION}/nodeTemplates/${GENERIC_ID}`]:
    'compute.googleapis.com/NodeTemplate',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}`]:
    'compute.googleapis.com/Project',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/regions/${TEST_REGION}/packetMirrorings/${GENERIC_ID}`]:
    'compute.googleapis.com/PacketMirroring',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/regions/${TEST_REGION}/disks/${GENERIC_ID}`]:
    'compute.googleapis.com/RegionDisk',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/reservations/${GENERIC_ID}`]:
    'compute.googleapis.com/Reservation',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/regions/${TEST_REGION}/resourcePolicies/${GENERIC_ID}`]:
    'compute.googleapis.com/ResourcePolicy',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/routes/${GENERIC_ID}`]:
    'compute.googleapis.com/Route',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/regions/${TEST_REGION}/routers/${GENERIC_ID}`]:
    'compute.googleapis.com/Router',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/securityPolicies/${GENERIC_ID}`]:
    'compute.googleapis.com/SecurityPolicy',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/snapshots/${GENERIC_ID}`]:
    'compute.googleapis.com/Snapshot',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/sslCertificates/${GENERIC_ID}`]:
    'compute.googleapis.com/SslCertificate',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/sslPolicies/${GENERIC_ID}`]:
    'compute.googleapis.com/SslPolicy',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/regions/${TEST_REGION}/subnetworks/${GENERIC_ID}`]:
    'compute.googleapis.com/Subnetwork',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/targetHttpProxies/${GENERIC_ID}`]:
    'compute.googleapis.com/TargetHttpProxy',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/targetHttpsProxies/${GENERIC_ID}`]:
    'compute.googleapis.com/TargetHttpsProxy',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/targetInstances/${GENERIC_ID}`]:
    'compute.googleapis.com/TargetInstance',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/regions/${TEST_REGION}/targetPools/${GENERIC_ID}`]:
    'compute.googleapis.com/TargetPool',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/targetTcpProxies/${GENERIC_ID}`]:
    'compute.googleapis.com/TargetTcpProxy',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/targetSslProxies/${GENERIC_ID}`]:
    'compute.googleapis.com/TargetSslProxy',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/regions/${TEST_REGION}/targetVpnGateways/${GENERIC_ID}`]:
    'compute.googleapis.com/TargetVpnGateway',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/global/urlMaps/${GENERIC_ID}`]:
    'compute.googleapis.com/UrlMap',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/regions/${TEST_REGION}/vpnGateways/${GENERIC_ID}`]:
    'compute.googleapis.com/VpnGateway',
  [`//compute.googleapis.com/projects/${TEST_PROJECT_ID}/regions/${TEST_REGION}/vpnTunnels/${GENERIC_ID}`]:
    'compute.googleapis.com/VpnTunnel',
  [`//appengine.googleapis.com/apps/${GENERIC_ID}`]:
    'appengine.googleapis.com/Application',
  [`//appengine.googleapis.com/apps/APP/services/${GENERIC_ID}`]:
    'appengine.googleapis.com/Service',
  [`//appengine.googleapis.com/apps/APP/services/${GENERIC_ID}/versions/${GENERIC_ID}`]:
    'appengine.googleapis.com/Version',
  [`//cloudbilling.googleapis.com/billingAccounts/${GENERIC_ID}`]:
    'cloudbilling.googleapis.com/BillingAccount',
  [`//storage.googleapis.com/${GENERIC_ID}`]: 'storage.googleapis.com/Bucket',
  [`//osconfig.googleapis.com/${GENERIC_ID}`]:
    'osconfig.googleapis.com/PatchDeployment',
  [`//dns.googleapis.com/projects/${TEST_PROJECT_ID}/managedZones/${GENERIC_ID}`]:
    'dns.googleapis.com/ManagedZone',
  [`//dns.googleapis.com/projects/${TEST_PROJECT_ID}/policies/${GENERIC_ID}`]:
    'dns.googleapis.com/Policy',
  [`//spanner.googleapis.com/projects/${TEST_PROJECT_ID}/instances/${GENERIC_ID}`]:
    'spanner.googleapis.com/Instance',
  [`//spanner.googleapis.com/projects/${TEST_PROJECT_ID}/instances/${GENERIC_ID}/databases/${GENERIC_ID}`]:
    'spanner.googleapis.com/Database',
  [`//spanner.googleapis.com/projects/${TEST_PROJECT_ID}/instances/${GENERIC_ID}/backups/${GENERIC_ID}`]:
    'spanner.googleapis.com/Backup',
  [`//bigquery.googleapis.com/projects/${TEST_PROJECT_ID}/datasets/${GENERIC_ID}`]:
    'bigquery.googleapis.com/Dataset',
  [`//bigquery.googleapis.com/projects/${TEST_PROJECT_ID}/datasets/${GENERIC_ID}/tables/${GENERIC_ID}`]:
    'bigquery.googleapis.com/Table',
  [`//iam.googleapis.com/projects/${TEST_PROJECT_ID}/roles/${GENERIC_ID}`]:
    'iam.googleapis.com/Role',
  [`//iam.googleapis.com/projects/${TEST_PROJECT_ID}/serviceAccounts/${GENERIC_ID}`]:
    'iam.googleapis.com/ServiceAccount',
  [`//iam.googleapis.com/projects/${TEST_PROJECT_ID}/serviceAccounts/${GENERIC_ID}/keys/${GENERIC_ID}`]:
    'iam.googleapis.com/ServiceAccountKey',
  [`//pubsub.googleapis.com/projects/${TEST_PROJECT_ID}/topics/${GENERIC_ID}`]:
    'pubsub.googleapis.com/Topic',
  [`//pubsub.googleapis.com/projects/${TEST_PROJECT_ID}/subscriptions/${GENERIC_ID}`]:
    'pubsub.googleapis.com/Subscription',
  [`//pubsub.googleapis.com/projects/${TEST_PROJECT_ID}/snapshots/${GENERIC_ID}`]:
    'pubsub.googleapis.com/Snapshot',
  [`//dataproc.googleapis.com/projects/${TEST_PROJECT_ID}/regions/${TEST_REGION}/clusters/${GENERIC_ID}`]:
    'dataproc.googleapis.com/Cluster',
  [`//dataproc.googleapis.com/projects/${TEST_PROJECT_ID}/regions/${TEST_REGION}/jobs/${GENERIC_ID}`]:
    'dataproc.googleapis.com/Job',
  [`//cloudkms.googleapis.com/projects/${TEST_PROJECT_ID}/locations/${TEST_LOCATION}/keyRings/${GENERIC_ID}`]:
    'cloudkms.googleapis.com/KeyRing',
  [`//cloudkms.googleapis.com/projects/${TEST_PROJECT_ID}/locations/${TEST_LOCATION}/keyRings/${GENERIC_ID}/cryptoKeys/${GENERIC_ID}`]:
    'cloudkms.googleapis.com/CryptoKey',
  [`//cloudkms.googleapis.com/projects/${TEST_PROJECT_ID}/locations/${TEST_LOCATION}/keyRings/${GENERIC_ID}/cryptoKeys/${GENERIC_ID}/cryptoKeyVersions/${GENERIC_ID}`]:
    'cloudkms.googleapis.com/CryptoKeyVersion',
  [`//cloudkms.googleapis.com/projects/${TEST_PROJECT_ID}/locations/${TEST_LOCATION}/keyRings/${GENERIC_ID}/importJobs/${GENERIC_ID}`]:
    'cloudkms.googleapis.com/ImportJob',
  [`//container.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/clusters/${GENERIC_ID}`]:
    'container.googleapis.com/Cluster',
  [`//container.googleapis.com/projects/${TEST_PROJECT_ID}/locations/${TEST_LOCATION}/clusters/${GENERIC_ID}`]:
    'container.googleapis.com/Cluster',
  [`//container.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/clusters/${GENERIC_ID}/nodePools/${GENERIC_ID}`]:
    'container.googleapis.com/NodePool',
  [`//cloudsql.googleapis.com/projects/${TEST_PROJECT_ID}/instances/${GENERIC_ID}`]:
    'sqladmin.googleapis.com/Instance',
  [`//bigtable.googleapis.com/projects/${TEST_PROJECT_ID}/instances/${GENERIC_ID}/appProfiles/${GENERIC_ID}`]:
    'bigtableadmin.googleapis.com/AppProfile',
  [`//bigtable.googleapis.com/projects/${TEST_PROJECT_ID}/instances/${GENERIC_ID}/clusters/${GENERIC_ID}/backups/${GENERIC_ID}`]:
    'bigtableadmin.googleapis.com/Backup',
  [`//bigtable.googleapis.com/projects/${TEST_PROJECT_ID}/instances/${GENERIC_ID}/clusters/${GENERIC_ID}`]:
    'bigtableadmin.googleapis.com/Cluster',
  [`//bigtable.googleapis.com/projects/${TEST_PROJECT_ID}/instances/${GENERIC_ID}`]:
    'bigtableadmin.googleapis.com/Instance',
  [`//bigtable.googleapis.com/projects/${TEST_PROJECT_ID}/instances/${GENERIC_ID}/tables/${GENERIC_ID}`]:
    'bigtableadmin.googleapis.com/Table',
  [`//container.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/clusters/${GENERIC_ID}/k8s/namespaces/${GENERIC_ID}/extensions/ingresses/${GENERIC_ID}`]:
    'extensions.k8s.io/Ingress',
  [`//container.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/clusters/${GENERIC_ID}/k8s/namespaces/${GENERIC_ID}/networking.k8s.io/ingresses/${GENERIC_ID}`]:
    'networking.k8s.io/Ingress',
  [`//container.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/clusters/${GENERIC_ID}/k8s/namespaces/${GENERIC_ID}/networking.k8s.io/networkpolicies/${GENERIC_ID}`]:
    'networking.k8s.io/Networkpolicy',
  [`//serviceusage.googleapis.com/projects/${TEST_PROJECT_NUMBER}/services/${GENERIC_ID}`]:
    'serviceusage.googleapis.com/Service',
  [`//datafusion.googleapis.com/projects/${TEST_PROJECT_ID}/locations/${TEST_LOCATION}/instances/${GENERIC_ID}`]:
    'datafusion.googleapis.com/Instance',
  [`//logging.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/buckets/${GENERIC_ID}`]:
    'logging.googleapis.com/LogBucket',
  [`//logging.googleapis.com/projects/${TEST_PROJECT_NUMBER}/sinks/${GENERIC_ID}`]:
    'logging.googleapis.com/LogSink',
  [`//logging.googleapis.com/folders/${GENERIC_ID}/sinks/${GENERIC_ID}`]:
    'logging.googleapis.com/LogSink',
  [`//logging.googleapis.com/organizations/${GENERIC_ID}/sinks/${GENERIC_ID}`]:
    'logging.googleapis.com/LogSink',
  [`//logging.googleapis.com/billingAccounts/${GENERIC_ID}/sinks/${GENERIC_ID}`]:
    'logging.googleapis.com/LogSink',
  [`//logging.googleapis.com/projects/${TEST_PROJECT_NUMBER}/metrics/${GENERIC_ID}`]:
    'logging.googleapis.com/LogMetric',
  [`//networkmanagement.googleapis.com/projects/${TEST_PROJECT_ID}/locations/global/connectivityTests/${GENERIC_ID}`]:
    'networkmanagement.googleapis.com/ConnectivityTest',
  [`//managedidentities.googleapis.com/projects/${TEST_PROJECT_ID}/locations/global/domains/${GENERIC_ID}`]:
    'managedidentities.googleapis.com/Domain',
  [`//privateca.googleapis.com/projects/${TEST_PROJECT_ID}/locations/${TEST_LOCATION}/caPools/${GENERIC_ID}`]:
    'privateca.googleapis.com/CaPool',
  [`//privateca.googleapis.com/projects/${TEST_PROJECT_ID}/locations/${TEST_LOCATION}/caPools/${GENERIC_ID}/certificateAuthorities/${GENERIC_ID}`]:
    'privateca.googleapis.com/CertificateAuthority',
  [`//privateca.googleapis.com/projects/${TEST_PROJECT_ID}/locations/${TEST_LOCATION}/caPools/${GENERIC_ID}/certificateAuthorities/${GENERIC_ID}/certificateRevocationLists/${GENERIC_ID}`]:
    'privateca.googleapis.com/CertificateRevocationList',
  [`//privateca.googleapis.com/projects/${TEST_PROJECT_ID}/locations/${TEST_LOCATION}/certificateTemplates/${GENERIC_ID}`]:
    'privateca.googleapis.com/CertificateTemplate',
  [`//dataflow.googleapis.com/projects/${TEST_PROJECT_ID}/locations/${TEST_LOCATION}/jobs/${GENERIC_ID}`]:
    'dataflow.googleapis.com/Job',
  [`//gameservices.googleapis.com/projects/${TEST_PROJECT_ID}/locations/global/realms/${GENERIC_ID}/gameServerClusters/${GENERIC_ID}`]:
    'gameservices.googleapis.com/GameServerCluster',
  [`//gameservices.googleapis.com/projects/${TEST_PROJECT_ID}/locations/global/realms/${GENERIC_ID}`]:
    'gameservices.googleapis.com/Realm',
  [`//gameservices.googleapis.com/projects/${TEST_PROJECT_ID}/locations/global/gameServerDeployments/${GENERIC_ID}/configs/${GENERIC_ID}`]:
    'gameservices.googleapis.com/GameServerConfig',
  [`//gameservices.googleapis.com/projects/${TEST_PROJECT_ID}/locations/global/gameServerDeployments/${GENERIC_ID}`]:
    'gameservices.googleapis.com/GameServerDeployment',
  [`//gkehub.googleapis.com/projects/${TEST_PROJECT_ID}/locations/global/memberships/${GENERIC_ID}`]:
    'gkehub.googleapis.com/Membership',
  [`//secretmanager.googleapis.com/projects/${TEST_PROJECT_NUMBER}/secrets/${GENERIC_ID}`]:
    'secretmanager.googleapis.com/Secret',
  [`//secretmanager.googleapis.com/projects/${TEST_PROJECT_NUMBER}/secrets/${GENERIC_ID}/versions/${GENERIC_ID}`]:
    'secretmanager.googleapis.com/SecretVersion',
  [`//tpu.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/nodes/${GENERIC_ID}`]:
    'tpu.googleapis.com/Node',
  [`//composer.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/environments/${GENERIC_ID}`]:
    'composer.googleapis.com/Environment',
  [`//file.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/instances/${GENERIC_ID}`]:
    'file.googleapis.com/Instance',
  [`//file.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/backups/${GENERIC_ID}`]:
    'file.googleapis.com/Backup',
  [`//servicedirectory.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/namespaces/${GENERIC_ID}`]:
    'servicedirectory.googleapis.com/Namespace',
  [`//assuredworkloads.googleapis.com/organizations/${GENERIC_ID}/locations/${TEST_LOCATION}/workloads/${GENERIC_ID}`]:
    'assuredworkloads.googleapis.com/Workload',
  [`//artifactregistry.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/repositories/${GENERIC_ID}/dockerimages/${GENERIC_ID}`]:
    'artifactregistry.googleapis.com/DockerImage',
  [`//artifactregistry.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/repositories/${GENERIC_ID}`]:
    'artifactregistry.googleapis.com/Repository',
  [`//apigateway.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/apis/${GENERIC_ID}`]:
    'apigateway.googleapis.com/Api',
  [`//apigateway.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/apis/${GENERIC_ID}/configs/${GENERIC_ID}`]:
    'apigateway.googleapis.com/ApiConfig',
  [`//apigateway.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/gateways/${GENERIC_ID}`]:
    'apigateway.googleapis.com/Gateway',
  [`//redis.googleapis.com/projects/${TEST_PROJECT_ID}/locations/${TEST_LOCATION}/instances/${GENERIC_ID}`]:
    'redis.googleapis.com/Instance',
  [`//memcache.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/instances/${GENERIC_ID}`]:
    'memcache.googleapis.com/Instance',
  [`//documentai.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/processors/${GENERIC_ID}/humanReviewConfig`]:
    'documentai.googleapis.com/HumanReviewConfig',
  [`//documentai.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/labelerPools/${GENERIC_ID}`]:
    'documentai.googleapis.com/LabelerPool',
  [`//documentai.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/processors/${GENERIC_ID}`]:
    'documentai.googleapis.com/Processor',
  [`//aiplatform.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/batchPredictionJobs/${GENERIC_ID}`]:
    'aiplatform.googleapis.com/BatchPredictionJob',
  [`//aiplatform.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/customJobs/${GENERIC_ID}`]:
    'aiplatform.googleapis.com/CustomJob',
  [`//aiplatform.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/dataLabelingJobs/${GENERIC_ID}`]:
    'aiplatform.googleapis.com/DataLabelingJob',
  [`//aiplatform.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/datasets/${GENERIC_ID}`]:
    'aiplatform.googleapis.com/Dataset',
  [`//aiplatform.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/endpoints/${GENERIC_ID}`]:
    'aiplatform.googleapis.com/Endpoint',
  [`//aiplatform.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/hyperparameterTuningJobs/${GENERIC_ID}`]:
    'aiplatform.googleapis.com/HyperparameterTuningJob',
  [`//aiplatform.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/models/${GENERIC_ID}`]:
    'aiplatform.googleapis.com/Model',
  [`//aiplatform.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/specialistPools/${GENERIC_ID}`]:
    'aiplatform.googleapis.com/SpecialistPool',
  [`//aiplatform.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/trainingPipelines/${GENERIC_ID}`]:
    'aiplatform.googleapis.com/TrainingPipeline',
  [`//monitoring.googleapis.com/projects/${TEST_PROJECT_NUMBER}/policies/${GENERIC_ID}`]:
    'monitoring.googleapis.com/AlertPolicy',
  [`//vpcaccess.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/connectors/${GENERIC_ID}`]:
    'vpcaccess.googleapis.com/Connector',
  [`//servicemanagement.googleapis.com/services/${GENERIC_ID}`]:
    'servicemanagement.googleapis.com/ManagedService',
  [`//eventarc.googleapis.com/projects/${TEST_PROJECT_NUMBER}/locations/${TEST_LOCATION}/triggers/${GENERIC_ID}`]:
    'eventarc.googleapis.com/Trigger',
  [`//container.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/clusters/${TEST_CLUSTER}/k8s/nodes/${GENERIC_ID}`]:
    'k8s.io/Node',
  [`//container.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/clusters/${TEST_CLUSTER}/k8s/namespaces/${GENERIC_ID}/pods/${GENERIC_ID}`]:
    'k8s.io/Pod',
  [`//container.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/clusters/${TEST_CLUSTER}/k8s/namespaces/${GENERIC_ID}`]:
    'k8s.io/Namespace',
  [`//container.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/clusters/${TEST_CLUSTER}/k8s/namespaces/${GENERIC_ID}/services/${GENERIC_ID}`]:
    'k8s.io/Service',
  [`//container.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/clusters/${TEST_CLUSTER}/k8s/namespaces/${GENERIC_ID}/rbac.authorization.k8s.io/roles/${GENERIC_ID}`]:
    'rbac.authorization.k8s.io/Role',
  [`//container.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/clusters/${TEST_CLUSTER}/k8s/namespaces/${GENERIC_ID}/rbac.authorization.k8s.io/rolebindings/${GENERIC_ID}`]:
    'rbac.authorization.k8s.io/RoleBinding',
  [`//container.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/clusters/${TEST_CLUSTER}/k8s/rbac.authorization.k8s.io/clusterroles/${GENERIC_ID}`]:
    'rbac.authorization.k8s.io/ClusterRole',
  [`//container.googleapis.com/projects/${TEST_PROJECT_ID}/zones/${TEST_ZONE}/clusters/${TEST_CLUSTER}/k8s/rbac.authorization.k8s.io/clusterrolebindings/${GENERIC_ID}`]:
    'rbac.authorization.k8s.io/ClusterRoleBinding',
};

describe('findResourceKindFromCloudResourceIdentifier', () => {
  for (const identifier of Object.keys(testResourceIdentifiers)) {
    it(`should find the correct identifier for ${testResourceIdentifiers[identifier]} resources`, () => {
      expect(findResourceKindFromCloudResourceIdentifier(identifier)).toEqual(
        testResourceIdentifiers[identifier],
      );
    });
  }
  it(`should return undefined if a resource map does not exist`, () => {
    expect(
      findResourceKindFromCloudResourceIdentifier(
        `//fakeapi.googleapis.com/projects/${TEST_PROJECT_ID}`,
      ),
    ).toBeUndefined();
  });
});
