export enum ServiceUsageListFilter {
  ENABLED = 'state:ENABLED',
  DISABLED = 'state:DISABLED',
}

export enum ServiceUsageName {
  CLOUD_FUNCTIONS = 'cloudfunctions.googleapis.com',
  STORAGE = 'storage.googleapis.com',
  STORAGE_COMPONENT = 'storage-component.googleapis.com',
  STORAGE_API = 'storage-api.googleapis.com',
  SERVICE_USAGE = 'serviceusage.googleapis.com',
  IAM = 'iam.googleapis.com',
  RESOURCE_MANAGER = 'cloudresourcemanager.googleapis.com',
  CLOUD_ASSET = 'cloudasset.googleapis.com',
  COMPUTE = 'compute.googleapis.com',
  KMS = 'cloudkms.googleapis.com',
  SQL_ADMIN = 'sqladmin.googleapis.com',
  BIG_QUERY = 'bigquery.googleapis.com',
  DNS = 'dns.googleapis.com',
  CONTAINER = 'container.googleapis.com',
  LOGGING = 'logging.googleapis.com',
  MONITORING = 'monitoring.googleapis.com',
  BINARY_AUTHORIZATION = 'binaryauthorization.googleapis.com',
  PUB_SUB = 'pubsub.googleapis.com',
  APP_ENGINE = 'appengine.googleapis.com',
  CLOUD_RUN = 'run.googleapis.com',
  REDIS = 'redis.googleapis.com',
  MEMCACHE = 'memcache.googleapis.com',
  SPANNER = 'spanner.googleapis.com',
  API_GATEWAY = 'apigateway.googleapis.com',
  PRIVATE_CA = 'privateca.googleapis.com',
  ACCESS_CONTEXT_MANAGER = 'accesscontextmanager.googleapis.com',
  DATAPROC_CLUSTERS = 'dataproc.googleapis.com',
  BIG_TABLE = 'bigtableadmin.googleapis.com',
  BILLING_BUDGET = 'billingbudgets.googleapis.com',
  CLOUD_BILLING = 'cloudbilling.googleapis.com',
  CLOUD_BUILD = 'cloudbuild.googleapis.com',
  SECRET_MANAGER = 'secretmanager.googleapis.com',
  CLOUD_SOURCE_REPOSITORIES = 'sourcerepo.googleapis.com',
  WEB_SECURITY_SCANNER = 'websecurityscanner.googleapis.com',
  ORG_POLICY = 'orgpolicy.googleapis.com',
}
