name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: setup-node
        name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Check out code repository source code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test:ci

      - name: Run build
        run: yarn build

  # Publishing is done in a separate job to allow
  # for all matrix builds to complete.
  BuildRelease:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    name: Checkout Code
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          token: ${{ secrets.AUTO_GITHUB_PAT_TOKEN }}
      - name: Build and Release
        uses: jupiterone/action-npm-build-release@v1
        with:
          npm_auth_token: ${{ secrets.NPM_AUTH_TOKEN }}
          gh_token: ${{ secrets.AUTO_GITHUB_PAT_TOKEN }}
