name: J1 Integration deployment

on:
  release:
    types:
      - published

jobs:
  j1-integration-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Get integration name
        id: get-integration-name
        shell: bash
        run: |
          NAME=${{ github.event.repository.name }}
          echo "integrationName=${NAME#graph-}" >> $GITHUB_OUTPUT
      - name: Get version number
        id: get-version-number
        shell: bash
        run: |
          TAG=${{ github.event.release.tag_name }}
          echo "versionNumber=${TAG#v}" >> $GITHUB_OUTPUT
      - name: Bump integration deployment version
        uses: JupiterOne/integration-github-actions/create-integration-deployment@v2.0.1
        with:
          integrationName:
            ${{ steps.get-integration-name.outputs.integrationName }}
          releaseNotes: ${{ github.event.release.body }}
          version: ${{ steps.get-version-number.outputs.versionNumber }}
          githubToken: ${{ secrets.AUTO_GITHUB_PAT_TOKEN }}
          npmAuthToken: ${{ secrets.NPM_AUTH_TOKEN }}
